{% set name = "zppy" %}
{% set version = "3.1.0rc1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/zppy/archive/v{{ version }}.tar.gz
  sha256: 0229a20ab20ac0545486140d61e870301e0ebf68a2ca08edf061daff52ec0bd4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  noarch: python
  entry_points:
    - zppy = zppy.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - configobj >=5.0.6
    - jinja2 >=3.1.2
    - mache >=1.3.2
    - mpas_tools >=0.15.0
    - pillow >=9.2.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - zppy
  commands:
    - zppy --help
    - pip check

about:
  home: https://github.com/E3SM-Project/zppy
  summary: 'E3SM post-processing toolchain'
  license: BSD-3-Clause AND custom
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
